### ISSUE TITLE
crash during importing the Notion pages

### ISSUE THREAD

**Issue by luvletter93** [anyproto/anytype-heart#1097]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

[crash_2024-04-09T12_44_42.log](https://github.com/anyproto/anytype-ts/files/14918725/crash_2024-04-09T12_44_42.log)

### Expected Behavior

import successfully 

### Steps To Reproduce

1. Import to Space 2. Select "Notion". 3.Paste token and click "import data"  4. Importing 5.crashed

### Environment

```markdown
- windows11 x64
- Version: 0.39.0
```

**Comment by AnastasiaShemyakinskaya** [comment]
Hello! Could you please try to use the latest anytype version?

**Comment by AshDevFr** [comment]
I have the same issue with `Anytype-0.40.8-mac-arm64`

Here is the stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x101a85fe0]

goroutine 1301 [running]:
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.statusItemOptions(0x18?, {0x1400d4a4570
?, 0x14000fb15f8?}, 0x100138ec0?)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:440 +0x20
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.getRelationOptions({0x10298d9e0?, 0x1400a36ab40?}, {0x1400d4a4570?, 0x12e3929e8?}, 0x14000fb16b8?)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:366 +0x124
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).provideRelationOptionsSnapshots(0x102576660?, {0x1400d4a4570, 0x18}, {0x10298d9e0, 0x1400a36ab40}, 0x14000f068a0)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:218 +0x11c
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).makeRelationFromProperty(0x1400aa476c0, 0x14000f068a0, {0x10298d9e0, 0x1400a36ab40}, 0x1400adc3b00, {0x1400a6dcfa6, 0x6}, 0x0, 0x1)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:185 +0x348
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).retrieveRelation(0x1400aa476c0, 0x1400af54800, {0x1400a6dcfa6, 0x6}, {0x10298d9e0, 0x1400a36ab40}, 0x1400adc3b00, 0x0, 0x1)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:160 +0x108
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).handlePageProperties(0x1400aa476c0, 0x1400af54800, 0x1400adc3b00)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:141 +0x138
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).provideDetails(0x1400aa476c0, 0x1400af54800)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:98 +0x50
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).makeSnapshotFromPages(0x1400aa476c0, 0x1400af54800, 0x1400ad313a0)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:83 +0x2c
github.com/anyproto/anytype-heart/core/block/import/notion/api/page.(*Task).Execute(0x1400aa476c0, {0x102471dc0?, 0x1400af54800})
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/notion/api/page/task.go:58 +0x78
github.com/anyproto/anytype-heart/core/block/import/common/workerpool.(*WorkerPool).works(0x14000805d60, {0x102471dc0, 0x1400af54800}, 0x1001a2398?)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/common/workerpool/workerpool.go:53 +0xa0
github.com/anyproto/anytype-heart/core/block/import/common/workerpool.(*WorkerPool).Start.func1(0x0?)
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/common/workerpool/workerpool.go:42 +0x2c
created by github.com/anyproto/anytype-heart/core/block/import/common/workerpool.(*WorkerPool).Start in goroutine 1280
	/Users/runner/work/anytype-heart/anytype-heart/core/block/import/common/workerpool/workerpool.go:41 +0x4c
```

**Comment by sashagood** [comment]
Fixed in PR #1247 (nil pointer fix in Notion import). Closing.
