### ISSUE TITLE
Crash in gRPC auth.go

### ISSUE THREAD

**Issue by grishy** [anyproto/anytype-heart#1521]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I found some logs with panic:
- [stack.20240828.220133.47.log](https://github.com/user-attachments/files/16788481/stack.20240828.220133.47.log)
- [stack.20240828.221512.16.log](https://github.com/user-attachments/files/16788482/stack.20240828.221512.16.log)

Looks similar:
```
goroutine 3967 [running]:
github.com/anyproto/anytype-heart/util/debug.Stack(0x1)
	/Users/runner/work/anytype-heart/anytype-heart/util/debug/debug.go:87 +0x68
github.com/anyproto/anytype-heart/util/debug.SaveStackToRepo({0x140046027c0?, 0x104d23d90?}, 0x1)
	/Users/runner/work/anytype-heart/anytype-heart/util/debug/debug.go:116 +0x164
github.com/anyproto/anytype-heart/core.(*Middleware).SaveGoroutinesStack(0x140046eb300?, {0x140046027c0?, 0x1334010c8?})
	/Users/runner/work/anytype-heart/anytype-heart/core/core.go:119 +0xc4
github.com/anyproto/anytype-heart/core.(*Middleware).DebugStackGoroutines(0x108e7edc0?, {0x107593440?, 0x8?}, 0x14000100008?)
	/Users/runner/work/anytype-heart/anytype-heart/core/debug.go:133 +0x24
github.com/anyproto/anytype-heart/pb/service._ClientCommands_DebugStackGoroutines_Handler.func1({0x1075cb260?, 0x140040118c0?}, {0x107468220?, 0x1400460a0d0?})
	/Users/runner/work/anytype-heart/anytype-heart/pb/service/service.pb.go:8008 +0xd0
main.main.appendInterceptor.func14({0x1075cb260?, 0x140040118c0?}, {0x107468220?, 0x1400460a0d0?}, 0x1070ce500?, 0x10759b5d0?)
	/Users/runner/work/anytype-heart/anytype-heart/cmd/grpcserver/grpc.go:264 +0x78
main.main.ChainUnaryServer.func17.1({0x1075cb260?, 0x140040118c0?}, {0x107468220?, 0x1400460a0d0?})
	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
github.com/anyproto/anytype-heart/metrics.SharedLongMethodsInterceptor({0x1075cb260, 0x14004010d80}, {0x107468220, 0x1400460a0d0}, {0x106a309ee, 0x14}, 0x140065de740)
	/Users/runner/work/anytype-heart/anytype-heart/metrics/interceptors.go:196 +0x258
github.com/anyproto/anytype-heart/metrics.LongMethodsInterceptor({0x1075cb260, 0x14004010d80}, {0x107468220, 0x1400460a0d0}, 0x14000c04780?, 0x140065de740)
	/Users/runner/work/anytype-heart/anytype-heart/metrics/interceptors.go:160 +0x7c
main.main.ChainUnaryServer.func17.1({0x1075cb260?, 0x14004010d80?}, {0x107468220?, 0x1400460a0d0?})
	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
github.com/anyproto/anytype-heart/core.(*Middleware).Authorize(0x140001865a0, {0x1075cb260, 0x14004010d80}, {0x107468220, 0x1400460a0d0}, 0x14004696788?, 0x140065de780)
	/Users/runner/work/anytype-heart/anytype-heart/core/auth.go:43 +0x268
main.main.func2({0x1075cb260?, 0x14004010d80?}, {0x107468220?, 0x1400460a0d0?}, 0x140046967d8?, 0x105b38b20?)
	/Users/runner/work/anytype-heart/anytype-heart/cmd/grpcserver/grpc.go:112 +0x4c
main.main.ChainUnaryServer.func17.1({0x1075cb260?, 0x14004010d80?}, {0x107468220?, 0x1400460a0d0?})
	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
github.com/anyproto/anytype-heart/metrics.SharedTraceInterceptor({0x1075cb260, 0x14004010d80}, {0x107468220, 0x1400460a0d0}, {0x106a309ee, 0x14}, 0x140065de7c0)
	/Users/runner/work/anytype-heart/anytype-heart/metrics/interceptors.go:65 +0xfc
github.com/anyproto/anytype-heart/metrics.UnaryTraceInterceptor({0x1075cb260, 0x14004010d80}, {0x107468220, 0x1400460a0d0}, 0x0?, 0x140065de7c0)
	/Users/runner/work/anytype-heart/anytype-heart/metrics/interceptors.go:51 +0x7c
main.main.ChainUnaryServer.func17({0x1075cb260, 0x14004010d80}, {0x107468220, 0x1400460a0d0}, 0x1400656ab00, 0x10747baa0?)
	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x114
github.com/anyproto/anytype-heart/pb/service._ClientCommands_DebugStackGoroutines_Handler({0x107593440, 0x140001865a0}, {0x1075cb260, 0x14004010d80}, 0x14004604080, 0x140006faea0)
	/Users/runner/work/anytype-heart/anytype-heart/pb/service/service.pb.go:8010 +0x148
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000752200, {0x1075cb260, 0x14004010cc0}, {0x1075dcb60, 0x140047641a0}, 0x14004ce25a0, 0x140006faff0, 0x108ed3fd8, 0x0)
	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1379 +0xb58
google.golang.org/grpc.(*Server).handleStream(0x14000752200, {0x1075dcb60, 0x140047641a0}, 0x14004ce25a0)
	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1790 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1029 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 3867
	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:1040 +0x13c
```

### Expected Behavior

Avoid panic 😄 

### Steps To Reproduce

1. Create self-hosted server
2. Try to connect

### Environment

```markdown
- OS: 14.6.1 (23G93)
- Version: 0.42.4
```

**Comment by deff7** [comment]
Hi! Can't see panic here, it's a goroutines stack.

Do you have a problem with connection to your server?
